# Generated by Django 4.0.3 on 2023-02-26 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imsApp', '0009_store_owner_alter_storeproduct_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.store'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('owner',)},
        ),
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('product', 'store')},
        ),
    ]
