# Generated by Django 4.0.3 on 2023-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0011_alter_storeproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product_image.png', upload_to='uploads/products/'),
        ),
    ]
