# Generated by Django 4.0.3 on 2023-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0012_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_product_image.png', null=True, upload_to='uploads/products/'),
        ),
    ]
