# Generated by Django 4.0.3 on 2023-03-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imsApp.store'),
        ),
    ]
