# Generated by Django 4.0.3 on 2023-03-05 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imsApp', '0014_stock_store'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
