# Generated by Django 4.0.3 on 2023-03-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0015_alter_store_unique_together_alter_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='storeproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.storeproduct'),
        ),
    ]
