# Generated by Django 4.0.3 on 2023-03-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0017_alter_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imsApp.store'),
        ),
    ]
